// To use this request file, you will need to install an extension called humao.Rest-client found at the following link:
// https://marketplace.visualstudio.com/items?itemName=humao.rest-client
###
// GET Route Index
GET http://localhost:3000/todos
###
// POST Route to create a To Do List
POST http://localhost:3000/todos HTTP/1.1
content-type: application/json

{
  "id": "0",
  "title": "ToDo Sample"
}
###
// POST Route to create a task on a To Do List
POST http://localhost:3000/todos/0/tasks HTTP/1.1
Content-Type: application/json

{
  "title": "New task"
}
###
// PUT route that change the title of the toDo
PUT http://localhost:3000/todos/0 HTTP/1.1
content-type: application/json

{
  "title": "first ToDo"
}
###
// PUT route to check error on requested ID
PUT http://localhost:3000/todos/k HTTP/1.1
content-type: application/json

{
  "title": "The K ToDo"
}
###
// DELETE route that delete a To Do List
DELETE http://localhost:3000/todos/0
